### ISSUE TITLE
Error in adding ServiceProvider Elimuswift\DbExporter\DbExportServiceProvider::class

### ISSUE THREAD

**Issue by shyaaam** [Elimuswift/db-exporter#4]
I found the correct file to be  DbExportHandlerServiceProvider. So the service provider that should be in the config/app.php is `"Elimuswift\DbExporter\DbExportHandlerServiceProvider::class"`

And the corresponding config publish command is 
`php artisan vendor:publish --provider="Elimuswift\DbExporter\ DbExportHandlerServiceProvider"`

Thanks

**Comment by weezqyd** [comment]
@pihyper Yeah will fix that.
