### ISSUE TITLE
Time fields not recognised?

### ISSUE THREAD

**Issue by longestdrive** [Elimuswift/db-exporter#6]
Thanks for the package - does exactly what I needed!

I've just created a migration from existing data - however it didn't appear to pick up time type fields. I had this in the migration file:
```
    $table->('am_tee')->nullable();
    $table->('end_time')->nullable();
```

I've edited the file manually in the meantime

**Comment by weezqyd** [comment]
Not all data types are supported at this moment, however I will update to to add more column data types. @
